sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                locale: ~
                currency:
                    options:
                        currencies: ['DKK']

                geographical:
                    options:
                        countries:
                            - "DK"
                            - "US"
                        zones:
                            US:
                                name: "Denmark"
                                countries:
                                    - "DK"
                setono_sylius_pickup_point_shipping_method:
                    options:
                        custom:
                            dao_pickup_point:
                                code: "dao_pickup_point"
                                name: "DAO with pickup points"
                                enabled: true
                                pickup_point_provider: dao
                                channels:
                                    - "FASHION_WEB"
                            gls_pickup_point:
                                code: "gls_pickup_point"
                                name: "GLS with pickup points"
                                enabled: true
                                pickup_point_provider: gls
                                channels:
                                    - "FASHION_WEB"
                            gls_home:
                                code: "gls_home"
                                name: "GLS home delivery"
                                enabled: true
                                channels:
                                    - "FASHION_WEB"
                            post_nord_pickup_point:
                                code: "post_nord_pickup_point"
                                name: "PostNord with pickup points"
                                enabled: true
                                pickup_point_provider: post_nord
                                channels:
                                    - "FASHION_WEB"
                            post_nord_home:
                                code: "post_nord_home"
                                name: "PostNord home delivery"
                                enabled: true
                                channels:
                                    - "FASHION_WEB"
                            faker:
                                code: "faker"
                                name: "Fake delivery"
                                enabled: true
                                pickup_point_provider: faker
                                channels:
                                    - "FASHION_WEB"
