sylius_fixtures:
    suites:
        default:
            fixtures:
                setono_sylius_pickup_point_shipping_method:
                    options:
                        custom:
                            dao_pickup_point:
                                code: "dao_pickup_point"
                                name: "DAO with pickup points"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: dao
                                channels:
                                    - "FASHION_WEB"
                            gls_pickup_point:
                                code: "gls_pickup_point"
                                name: "GLS with pickup points"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: gls
                                channels:
                                    - "FASHION_WEB"
                            gls_home:
                                code: "gls_home"
                                name: "GLS home delivery"
                                enabled: true
                                zone: "WORLD"
                                channels:
                                    - "FASHION_WEB"
                            post_nord_pickup_point:
                                code: "post_nord_pickup_point"
                                name: "PostNord with pickup points"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: post_nord
                                channels:
                                    - "FASHION_WEB"
                            post_nord_home:
                                code: "post_nord_home"
                                name: "PostNord home delivery"
                                enabled: true
                                zone: "WORLD"
                                channels:
                                    - "FASHION_WEB"
                            faker:
                                code: "faker"
                                name: "Fake delivery"
                                enabled: true
                                zone: "WORLD"
                                pickup_point_provider: faker
                                channels:
                                    - "FASHION_WEB"
