Setono\SyliusPickupPointPlugin\PickupPoint\PickupPoint:
    exclusion_policy: ALL
    xml_root_name: setono_sylius_pickup_point
    virtual_properties:
        getId:
            serialized_name: id
            type: string
            groups: [Detailed, Autocomplete]
        getLocation:
            serialized_name: location
            type: string
            groups: [Detailed, Autocomplete]
